### PR TITLE
Fix vulnerable packages where possible

### PR DESCRIPTION
**Pull request by tim-s-ccs**
I followed the instructions on snyk which was to relock our lockfile, reinstalling and running snyk wizard.

Before:
Tested 448 dependencies for known issues, found 12 issues, 14 vulnerable paths.

After:
Tested 411 dependencies for known issues, found 2 issues, 4 vulnerable paths.

### CODE REVIEW

**Review by bjgill — APPROVED** [review]
This is basically unreviewable. But can't see anything obviously wrong at a quick skim. :shipit:

**Comment by tim-s-ccs** [comment]
> This is basically unreviewable. But can't see anything obviously wrong at a quick skim. :shipit:

I will probably be doing this for several other repos, is it still worth getting a review for them? I can't imagine them being much different than this one.

**Comment by bjgill** [comment]
> > This is basically unreviewable. But can't see anything obviously wrong at a quick skim. :shipit:
> 
> I will probably be doing this for several other repos, is it still worth getting a review for them? I can't imagine them being much different than this one.

I think (hope?) the branch protection rules enforce needing to get a review. And even a brief skim to check for obvious problems is better than nothing.

**Comment by tim-s-ccs** [comment]
> I will probably be doing this for several other repos, is it still worth getting a review for them? I can't imagine them being much different than this one.

I understand, there is always the chance I'll mess something up, even if it is really only Snyk that is doing any code changes

**Pull request merged**
